before_script:
  - apt-get update && apt-get install -y postgresql-client
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go mod download

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"
    POSTGRES_DB: "deas_rss_test"
    POSTGRES_USER: runner
    POSTGRES_PASSSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust
    TEST_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

# Golang version choice helper
.use-golang-image: &use-golang-latest
  image: golang:latest

.use-golang-image: &use-golang-1-15
  image: golang:1.15

test:
  # Change to "<<: *use-golang-latest" to use the latest Go version
  <<: *use-golang-1-15
  <<: *test-vars
  stage: test
  services:
    - postgres:latest
  script:
    - buffalo test
