---
development:
  dialect: postgres
  database: deas_rss_development
  user: deas_rss
  # password:
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://deas_rss:@127.0.0.1:5432/deas_rss_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://deas_rss:@127.0.0.1:5432/deas_rss_production?sslmode=disable"}}
