package actions

import (
	"fmt"
	"net/http"

	"deas_rss/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Article)
// DB Table: Plural (articles)
// Resource: Plural (Articles)
// Path: Plural (/articles)
// View Template Folder: Plural (/templates/articles/)

// ArticlesResource is the resource for the Article model
type ArticlesResource struct {
	buffalo.Resource
}

// List gets all Articles. This function is mapped to the path
// GET /articles
func (v ArticlesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	articles := &models.Articles{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Add search if requested
	if c.Param("q") != "" {
		search := "%" + c.Param("q") + "%"
		q = q.Where("title ILIKE ? OR description ILIKE ? OR content ILIKE ?", search, search, search)
	}

	// Retrieve all Articles from the DB
	if err := q.All(articles); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("articles", articles)
		return c.Render(http.StatusOK, r.HTML("/articles/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(articles))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(articles))
	}).Respond(c)
}

// Show gets the data for one Article. This function is mapped to
// the path GET /articles/{article_id}
func (v ArticlesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Article
	article := &models.Article{}

	// To find the Article the parameter article_id is used.
	if err := tx.Find(article, c.Param("article_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("article", article)

		return c.Render(http.StatusOK, r.HTML("/articles/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(article))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(article))
	}).Respond(c)
}

// New renders the form for creating a new Article.
// This function is mapped to the path GET /articles/new
func (v ArticlesResource) New(c buffalo.Context) error {
	c.Set("article", &models.Article{})

	return c.Render(http.StatusOK, r.HTML("/articles/new.plush.html"))
}

// Create adds a Article to the DB. This function is mapped to the
// path POST /articles
func (v ArticlesResource) Create(c buffalo.Context) error {
	// Allocate an empty Article
	article := &models.Article{}

	// Bind article to the html form elements
	if err := c.Bind(article); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(article)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("article", article)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/articles/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "article.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/articles/%v", article.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(article))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(article))
	}).Respond(c)
}

// Edit renders a edit form for a Article. This function is
// mapped to the path GET /articles/{article_id}/edit
func (v ArticlesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Article
	article := &models.Article{}

	if err := tx.Find(article, c.Param("article_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("article", article)
	return c.Render(http.StatusOK, r.HTML("/articles/edit.plush.html"))
}

// Update changes a Article in the DB. This function is mapped to
// the path PUT /articles/{article_id}
func (v ArticlesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Article
	article := &models.Article{}

	if err := tx.Find(article, c.Param("article_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Article to the html form elements
	if err := c.Bind(article); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(article)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("article", article)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/articles/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "article.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/articles/%v", article.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(article))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(article))
	}).Respond(c)
}

// Destroy deletes a Article from the DB. This function is mapped
// to the path DELETE /articles/{article_id}
func (v ArticlesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Article
	article := &models.Article{}

	// To find the Article the parameter article_id is used.
	if err := tx.Find(article, c.Param("article_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(article); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "article.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/articles")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(article))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(article))
	}).Respond(c)
}
